repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.4.2
  hooks:
    # Run the linter.
    - id: ruff
      args: [ "--fix", "--config", "~/.ruff.toml" ]
    # Run the formatter.
    - id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.10.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
