from mdsort import settings

MEDIA_SUFFIX = settings.MEDIA_FILES_SUFFIXES[0]
MEDIA_INDICATOR = settings.DOWNLOADED_MEDIA_INDICATORS[0]
DOWNLOADED_MEDIA_FILE = (
    f"S.W.A.T.2017.S07E10.{MEDIA_INDICATOR}.HDTV.x265-MiNX[TGx]{MEDIA_SUFFIX}"
)
DOWNLOADED_MEDIA_DIRECTORY = f"The.Mandalorian.S02E02.Chapter.10.{MEDIA_INDICATOR}.WEB-DL.DDP.5.1.Atmos.H.264-PHOENiX"
PERSONAL_MEDIA_DIRECTORY = "Wedding Videos"
DOWNLOADED_APP_DIRECTORY = "Photoshop CS2"
MOVIES_DIRECTORY = "Movies"
A_MOVIE_DIRECTORY = (
    "Nosferatu (2024) (1080p MA WEB-DL x265 10bit EAC3 Atmos 5.1 Ghost) [QxR]"
)
PARENT_IDENTIFIER = settings.PARENT_IDENTIFIER
SERIES_DIRECTORY = "Catch 22"
PARENT_SERIES_DIRECTORY_STR_1 = "Mandalorian 2018"
PARENT_SERIES_DIRECTORY_STR_2 = "Avatar: The Last Airbender tt9018736"
